name: Dockerfile lint

on:
  push:
    branches: [main]
    paths: [Dockerfile, .dockerignore]
  pull_request:
    paths: [Dockerfile, .dockerignore]

jobs:
  droast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: immanuwell/dockerfile-roast@1.0.0
        with:
          files: Dockerfile
          min-severity: info
